@startuml
title WarmHouse Context Diagram

top to bottom direction

!include ./C4_Context.puml

Person(user, "User", "A user of the warm house system")
System(WarmHouseSystem, "WarmHouse System", "Warm house management system")

System_Ext(sensor, "Sensor", "Temperature Sensor API ", "Uses REST API, JSON data format")
Rel(user, WarmHouseSystem, "Uses the system")
Rel(WarmHouseSystem,sensor,"Fetches temperature")

@enduml