@startuml

!include ./C4_Container.puml
title Container Diagram for WarmHouse system

AddElementTag("microService", $shape=EightSidedShape(), $bgColor="CornflowerBlue", $fontColor="white", $legendText="micro service\neight sided")
AddElementTag("storage", $shape=RoundedBoxShape(), $bgColor="lightSkyBlue", $fontColor="white")


Person(user, User/Admin, "Пользователь умного дома")

System_Boundary(c1, "WarmHouse") {
    Container(web_app, "Web-App", "Javascript, Angular", "Веб-интерфейс для управления умным домом")

    Container(api_gateway, "ApiGateway", "Go", "Балансировщик, отвечающий за аутентификацию и маршрутизацию")


    Container(profile_service, "Profile Service", "Go", "Регистрация пользователей, хранение связи между устройством и клиентом, уведомления пользователю", $tags = "microService")
    ContainerDb(profiles_db, "Profiles DB", "PostgreSQL", "", $tags = "storage")

    Container(device_management_service, "DeviceManagement Service", "Go", "Регистрация и управление устройствами\nХранение метаданных устройств", $tags = "microService")
    ContainerDb(devices_db, "Devices DB", "PostgreSQL", "", $tags = "storage")
    ContainerDb(video_db, "Video DB", "Amazon S3", "", $tags = "storage")

    Container(automation_service, "Automation Service", "Go", "Создание пользовательских сценариев\nЗапуск сценариев по времени, триггерам или вручную", $tags = "microService")
    ContainerDb(automation_db, "Automation DB", "PostgreSQL", "", $tags = "storage")

    Container(telemetry_service, "Telemetry Service", "Go", "Сбор данных с устройств", $tags = "microService")
    ContainerDb(telemetry_db, "Telemetry DB", "ClickHouse", "", $tags = "storage")
    ContainerQueue(kafka, "kafka", "kafka")
    ContainerQueue(mqtt, "MQTT", "MQTT")
}

Boundary(c2, "Устройства") {
    Container_Ext(gate, "Котроллер открытия/закрытия ворот")
    Container_Ext(light, "Свет")
    Container_Ext(camera, "Камера")
    Container_Ext(heating_system, "Система отопления")
    Container_Ext(temperature_sensor, "Датчик температуры")
}

Rel_D(user, web_app, "Взаимодействует с сайтом", "HTTPS, WebBrowser")
Rel_D(web_app, api_gateway, "Отправляет запрос в платформу", "JSON/HTTPS")

Rel_R(api_gateway, profile_service, "Uses", "JSON/HTTPS")
Rel(api_gateway, automation_service, "Uses", "JSON/HTTPS")
Rel(api_gateway, device_management_service, "Uses", "JSON/HTTPS")
Rel(api_gateway, telemetry_service, "Uses", "JSON/HTTPS")
Rel_R(profile_service, profiles_db,)
Rel_D(device_management_service, devices_db,)
Rel_D(device_management_service, video_db,)
Rel(automation_service, automation_db,)
Rel(telemetry_service, telemetry_db,)

Rel(device_management_service, kafka, "")
Rel(automation_service, kafka, "")
Rel(profile_service, kafka, "")

Rel(mqtt, telemetry_service, "")
Rel(device_management_service, mqtt, "")
Rel(mqtt, automation_service, "")

Rel(device_management_service, camera, "")
BiRel(mqtt, light, "")
BiRel(mqtt, gate, "")
BiRel(mqtt, heating_system, "")
BiRel(mqtt, temperature_sensor, "")

Lay_R(telemetry_service, automation_service )
Lay_R(automation_service, device_management_service)
Lay_D(kafka,mqtt)

@enduml