openapi: 3.0.1
info:
  title: WarmHouse Services Api
  description: WarmHouse Services Api
  version: 1.0.0
tags:
  - name: DeviceManagement Service
  - name: Automation Service
  - name: Telemetry Service
  - name: Profile Service
paths:
  /devices:
    get:
      tags:
        - DeviceManagement Service
      summary: Получение списка устройств
      description: ''
      operationId: GetDevices
      parameters:
        - name: house_id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
        '400':
          description: Invalid format
        '404':
          description: Not found response
    post:
      tags:
        - DeviceManagement Service
      summary: Создание нового устройства
      description: ''
      operationId: CreateDevice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceCreate'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '400':
          description: Invalid format
        '404':
          description: Not found response
  /devices/{device_id}:
    parameters:
      - $ref: '#/components/parameters/device_id'
    get:
      tags:
        - DeviceManagement Service
      summary: Получение устройства по id
      description: ''
      operationId: GetDeviceById
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '400':
          description: Invalid format
        '404':
          description: Not found response
    patch:
      tags:
        - DeviceManagement Service
      summary: Обновление устройства
      description: ''
      operationId: UpdateDevice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceUpdate'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '400':
          description: Invalid format
        '404':
          description: Not found
        '500':
          $ref: '#/components/responses/UnexpectedError'
    delete:
      tags:
        - DeviceManagement Service
      summary: Удаление устройства
      description: ''
      operationId: DeleteDevice
      parameters:
        - $ref: '#/components/parameters/device_id'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid format
        '404':
          description: Not found
        '500':
          $ref: '#/components/responses/UnexpectedError'
  /devices/{device_id}/command:
    parameters:
      - $ref: '#/components/parameters/device_id'
    post:
      tags:
        - DeviceManagement Service
      summary: Отправка команды на устройство
      description: ''
      operationId: SendDeviceCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceCommand'
      responses:
        '200':
          description: Команда успешно отправлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResponse'
        '400':
          description: Неверный формат команды
        '404':
          description: Устройство не найдено
        '500':
          description: Ошибка при выполнении команды
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandError'

  /profiles:
    post:
      tags:
        - Profile Service
      summary: Создание профиля пользователя
      description: ''
      operationId: CreateUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileCreate'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Profile'
        '400':
          description: Invalid format

  /scenarios:
    get:
      tags:
        - Automation Service
      summary: Получение списка сценариев
      description: ''
      operationId: GetScenarios
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Scenario'
        '400':
          description: Invalid format
        '404':
          description: Not found response
    post:
      tags:
        - Automation Service
      summary: Создание нового сценария
      description: ''
      operationId: CreateScenario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScenarioCreate'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scenario'
        '400':
          description: Invalid format
        '404':
          description: Not found response
  /scenarios/{scenario_id}:
    parameters:
      - $ref: '#/components/parameters/scenario_id'
    get:
      tags:
        - Automation Service
      summary: Получение сценария по id
      description: ''
      operationId: GetScenarioById
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scenario'
        '400':
          description: Invalid format
        '404':
          description: Not found response
    patch:
      tags:
        - Automation Service
      summary: Обновление сценария
      description: ''
      operationId: UpdateScenario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScenarioUpdate'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scenario'
        '400':
          description: Invalid format
        '404':
          description: Not found
        '500':
          $ref: '#/components/responses/UnexpectedError'
    delete:
      tags:
        - Automation Service
      summary: Удаление сценария
      description: ''
      operationId: DeleteScenario
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid format
        '404':
          description: Not found
        '500':
          $ref: '#/components/responses/UnexpectedError'

  /telemetry:
    get:
      tags:
        - Telemetry Service
      summary: Получение списка телеметрии
      description: ''
      operationId: GetTelemetry
      parameters:
        - name: device_id
          in: query
          required: false
          description: Фильтр по device_id
          schema:
            type: string
            format: uuid
        - name: event_type
          in: query
          required: false
          description: Фильтр по типу события
          schema:
            type: string
        - name: from_date
          in: query
          required: false
          description: Начальная дата для фильтрации
          schema:
            type: string
            format: date-time
        - name: to_date
          in: query
          required: false
          description: Конечная дата для фильтрации
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Telemetry'
        '400':
          description: Invalid format
        '404':
          description: Not found response
  /telemetry/{telemetry_id}:
    parameters:
      - $ref: '#/components/parameters/telemetry_id'
    get:
      tags:
        - Telemetry Service
      summary: Получение записи телеметрии по id
      description: ''
      operationId: GetTelemetryById
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Telemetry'
        '400':
          description: Invalid format
        '404':
          description: Not found response
    delete:
      tags:
        - Telemetry Service
      summary: Удаление записи телеметрии
      description: ''
      operationId: DeleteTelemetry
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid format
        '404':
          description: Not found
        '500':
          $ref: '#/components/responses/UnexpectedError'

components:
  schemas:
    Device:
      title: Device
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          example: f4f98b69-5ab4-49e6-831b-f102f24287f0
        name:
          type: string
          minimum: 1
          maximum: 128
          example: Датчик температуры в спальне
        description:
          type: string
        house_id:
          type: string
          format: uuid
          example: f4f98b69-5ab4-49e6-831b-f102f24287f0
        type:
          type: string
          enum:
            - temperature_sensor
            - camera
        status:
          type: string
          enum:
            - 'on'
            - 'off'
        serial_number:
          type: string
          example: 1
        mac_address:
          type: string
          example: str
        manufacturer:
          type: string
          example: manufacturer
        model:
          type: string
          example: model
        ip_address:
          type: string
          example: 192.168.111.111
        properties:
          type: array
          items:
            $ref: '#/components/schemas/DeviceProperty'
        functions:
          type: array
          items:
            $ref: '#/components/schemas/DeviceFunction'
    DeviceProperty:
      title: DeviceProperty
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
          example: f4f98b69-5ab4-49e6-831b-f102f24287f0
        name:
          type: string
          minimum: 1
          maximum: 128
          example: temperature
        description:
          type: string
          example: Текущая температура в Цельсиях
        type:
          type: string
          enum:
            - value
            - event
          example: value
        value_unit:
          type: string
          enum:
            - number
            - string
            - bool
          example: number
      required:
        - name
        - type
    DeviceFunction:
      title: DeviceFunction
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
          example: f4f98b69-5ab4-49e6-831b-f102f24287f0
        name:
          type: string
          minimum: 1
          maximum: 128
          example: Управление питанием
        description:
          type: string
          example: Включение/выключение устройства
        type:
          type: string
          enum:
            - on_off
            - mode
            - range
            - toggle
            - video_stream
          example: on_off
        parameters:
          type: object
          additionalProperties: true
          example: {"param_1": 0}
      required:
        - name
        - type
    DeviceCreate:
      allOf:
        - $ref: '#/components/schemas/Device'
        - type: object
          required:
            - name
            - house_id
            - type
            - serial_number
            - mac_address
            - model
            - ip_address
    DeviceUpdate:
      allOf:
        - $ref: '#/components/schemas/Device'

    DeviceCommand:
      type: object
      properties:
        function_id:
          type: string
          format: uuid
          description: ID функции устройства
          example: f4f98b69-5ab4-49e6-831b-f102f24287f0
        parameters:
          type: object
          additionalProperties: true
          description: Параметры команды
          example: {"prop": 100}
      required:
        - function_id
    CommandResponse:
      type: object
      properties:
        command_id:
          type: string
          format: uuid
          example: f4f98b69-5ab4-49e6-831b-f102f24287f0
        status:
          type: string
          example: "done"
        success:
          type: boolean
          example: true
        timestamp:
          type: string
          format: date-time
          example: "2023-01-01T13:00:00Z"
    CommandError:
      type: object
      properties:
        code:
          type: string
          example: "DEVICE_UNAVAILABLE"
        message:
          type: string
          example: "Устройство недоступно"

    Profile:
      title: Profile
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          example: f4f98b69-5ab4-49e6-831b-f102f24287f0
        full_name:
          type: string
          example: string
        email:
          type: string
          example: string
        phone:
          type: string
          example: string
        password:
          type: string
          writeOnly: true
    ProfileCreate:
      allOf:
        - $ref: '#/components/schemas/Profile'
        - type: object
          required:
            - full_name
            - email
            - phone
            - password

    Scenario:
      title: Scenario
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
          example: f4f98b69-5ab4-49e6-831b-f102f24287f0
        name:
          type: string
          minLength: 1
          maxLength: 128
          example: "Автоматическое освещение"
        is_active:
          type: boolean
          example: true
        trigger_logic:
          type: string
          enum: [and, or]
          example: "and"
        triggers:
          type: array
          items:
            $ref: '#/components/schemas/ScenarioTrigger'
        actions:
          type: array
          items:
            $ref: '#/components/schemas/ScenarioAction'

    ScenarioTrigger:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
          example: f4f98b69-5ab4-49e6-831b-f102f24287f0
        trigger_type:
          type: string
          enum: [device_property, scheduler]
          example: "device_property"
        device_property_id:
          type: string
          format: uuid
          example: f4f98b69-5ab4-49e6-831b-f102f24287f0
        property_condition:
          type: string
          enum: [equals, greater_than, less_than]
          example: "equals"
        property_value:
          type: string
          example: "22"
        scheduler:
          type: object
          properties:
            start_time:
              type: string
              format: time
              example: "18:00:00"
            end_time:
              type: string
              format: time
              example: "23:00:00"
            days_of_week:
              type: array
              items:
                type: string
                enum: [monday, tuesday, wednesday, thursday, friday, saturday, sunday]
              example: ["monday", "tuesday", "wednesday", "thursday", "friday"]


    ScenarioAction:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
          example: f4f98b69-5ab4-49e6-831b-f102f24287f0
        device_function_id:
          type: string
          format: uuid
          example: f4f98b69-5ab4-49e6-831b-f102f24287f0
        action_value:
          type: string
          example: "on"
        action_order:
          type: integer
          minimum: 1
          example: 1

    ScenarioCreate:
      allOf:
        - $ref: '#/components/schemas/Scenario'
        - type: object
          required:
            - name
            - trigger_logic
            - triggers
            - actions

    ScenarioUpdate:
      allOf:
        - $ref: '#/components/schemas/Scenario'

    Telemetry:
      title: Telemetry
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
          example: f4f98b69-5ab4-49e6-831b-f102f24287f0
        device_id:
          type: string
          format: uuid
          example: f4f98b69-5ab4-49e6-831b-f102f24287f0
        event_type:
          type: string
          example: "sensors_data"
        event:
          type: string
          example: "Temperature changed"
        data:
          type: object
          additionalProperties: true
          example: {"value": 12.1, "unit": "Celsius"}
        created_at:
          type: string
          format: date-time
          readOnly: true
          example: "2023-01-01T12:00:00Z"

    Error:
      title: Error
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: '1000'
        message:
          type: string
          example: Ошибка
  parameters:
    device_id:
      name: device_id
      in: path
      required: true
      description: ''
      schema:
        type: string
        format: uuid
    user_id:
      name: user_id
      in: path
      required: true
      description: ''
      schema:
        type: string
        format: uuid
    house_id:
      name: house_id
      in: path
      required: true
      description: ''
      schema:
        type: string
        format: uuid
    scenario_id:
      name: scenario_id
      in: path
      required: true
      description: ''
      schema:
        type: string
        format: uuid
    telemetry_id:
      name: telemetry_id
      in: path
      required: true
      description: ''
      schema:
        type: string
        format: uuid
  responses:
    UnexpectedError:
      description: Unexpected Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt