@startuml

skinparam linetype ortho


entity users {
  *id : uuid <<PK>>
  --
  *full_name : text
  *email : text
  *password_hash : string
}

entity houses {
  *id : uuid <<PK>>
  --
  *user_id : uuid <<FK>>
  *name : text
}

entity devices {
  *id : uuid  <<PK>>
  --
  *name : text
  description : text
  *status : enum (on/off)
  *type : str
  *manufacturer : text
  *model : text
  *serial_number : text
  ip_address : text
  *mac_address : text
  *house_id : uuid <<FK>>
}

entity device_functions {
  *function_id : uuid  <<PK>>
  --
  *device_id : uuid <<FK>>
  *type : enum
  parameters : jsonb
}

entity device_properties {
  *property_id : uuid  <<PK>>
  --
  *device_id : uuid <<FK>>
  *name : text
  *type : enum
  value_unit : enum
}

entity scenarios {
  *id : uuid  <<PK>>
  --
  *name : text
  *is_active : bool
  *trigger_logic : enum
}

entity scenario_triggers {
  *id : uuid  <<PK>>
  --
  *scenario_id : uuid <<FK>>
  *trigger_type : enum
  --
  device_property_id : uuid <<FK>>
  property_condition : enum
  property_value : text
  --
  scheduler_id : uuid <<FK>>
}

entity schedulers {
  *id : uuid  <<PK>>
  --
  *start_time : time
  end_time : time
  days_of_week : text
}

entity scenario_actions {
  *id : uuid  <<PK>>
  --
  *scenario_id : uuid <<FK>>
  *device_function_id : uuid <<FK>>
  *action_value : text
  *action_order : integer
}

entity telemetry_data {
  *id : uuid  <<PK>>
  --
  *device_id : uuid <<FK>>
  *event_type : text
  *event : text
  *data : jsonb
}

users               ||--o{   houses
houses              ||--o{   devices
devices             ||--|{   device_functions
devices             ||--o{   device_properties
scenarios           ||--|{   scenario_triggers
scenarios           ||--o{   scenario_actions
device_properties   ||--o{   scenario_triggers
schedulers          |o--     scenario_triggers
device_functions    ||--o{   scenario_actions
devices             ||--o{   telemetry_data

@enduml